services:
  coresport-db:
    image: postgres:latest
    container_name: cs-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coresport
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql:ro
      - postgres-data:/var/lib/postgresql/data
  coresport-redis:
    image: redis:latest
    container_name: cs-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
    postgres-data: {}
    redis-data: {}