server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coresport
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  application:
    name: CoreSport
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true


